version: '3.8'
services:
  db_test:
    image: postgres:12-alpine
    volumes:
      - database_test:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    expose:
      - "5432"
  api_test:
    image: api_test
    build:
      context: .
      dockerfile: Dockerfile-test
    environment:
      - PORT=8000
      - DB_HOST=db_test
      - DB_USERNAME
      - DB_PASSWORD
    depends_on:
      - db_test
    ports:
      - "8000:8000"

volumes:
  database_test:
