version: '3.8'
services:
  db:
    image: postgres:12-alpine
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    ports:
      - "5432:5432"

volumes:
  database:
